import { VisualizationRegistryEntry } from '@/types/visualization';

export const VISUALIZATION_REGISTRY: Record<string, VisualizationRegistryEntry> = {
  'perf-trend': {
    id: 'perf-trend',
    type: 'area',
    inputViewModel: 'PerformanceHistoryViewModel',
    requiredFields: ['date', 'ctl', 'atl', 'tsb'],
    theme: 'slate',
    version: '1.0.0',
  },
  'pacing-variability': {
    id: 'pacing-variability',
    type: 'scatter',
    inputViewModel: 'ActivityPacingViewModel',
    requiredFields: ['distance', 'pace', 'hr'],
    theme: 'high-contrast',
    version: '1.0.0',
  },
  'power-curve': {
    id: 'power-curve',
    type: 'line',
    inputViewModel: 'MeanMaximalPowerViewModel',
    requiredFields: ['duration', 'watts', 'wattsKg'],
    theme: 'slate',
    version: '1.0.0',
  },
  'decoupling': {
    id: 'decoupling',
    type: 'line',
    inputViewModel: 'AerobicDecouplingViewModel',
    requiredFields: ['time', 'efficiencyFactor', 'decouplingPercent'],
    theme: 'high-contrast',
    version: '1.0.0',
  },
  'zone-distribution': {
    id: 'zone-distribution',
    type: 'zone-distribution',
    inputViewModel: 'ZoneDistributionViewModel',
    requiredFields: ['zone', 'timeInZone', 'percentTime'],
    theme: 'slate',
    version: '1.0.0',
  },
  'season-bests': {
    id: 'season-bests',
    type: 'bar',
    inputViewModel: 'SeasonBestsViewModel',
    requiredFields: ['distance', 'time', 'date'],
    theme: 'slate',
    version: '1.0.0',
  },
  'rolling-trend': {
    id: 'rolling-trend',
    type: 'rolling-trend',
    inputViewModel: 'RollingTrendViewModel',
    requiredFields: ['week', 'distance', 'movingTime', 'tss'],
    theme: 'slate',
    version: '1.0.0',
  },
  'elevation-profile': {
    id: 'elevation-profile',
    type: 'elevation-profile',
    inputViewModel: 'ElevationProfileViewModel',
    requiredFields: ['distance', 'elevation', 'grade'],
    theme: 'slate',
    version: '1.0.0',
  },
  'gauge-recovery': {
    id: 'gauge-recovery',
    type: 'gauge',
    inputViewModel: 'RecoveryScoreViewModel',
    requiredFields: ['score', 'hrv', 'sleepDuration'],
    theme: 'high-contrast',
    version: '1.0.0',
  },
};
