import { WidgetMetadata } from '@/types/widget';

/**
 * Registry of all 37 Track.Studio widgets with detailed Phase 12 metadata.
 */
export const WIDGET_METADATA_REGISTRY: Record<string, WidgetMetadata> = {
  // Home widgets
  home_profile: {
    id: 'home_profile',
    title: 'Athlete Profile Context',
    subtitle: 'Physiological profile and biometric invariants',
    category: 'Core Workspace',
    description: 'Displays basic physiological capacities, weight metrics, and active athlete records.',
    version: '1.0.0',
    ownerDashboards: ['dashboard'],
    requiredViewModel: 'HomeDashboardViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Provides structural context for physiological normalization, ensuring weight and gender indices are in lockstep.',
    defaultWidth: 2,
    defaultHeight: 1
  },
  home_recent_activity: {
    id: 'home_recent_activity',
    title: 'Recent Ingested Activity',
    subtitle: 'Pristine raw feed webhook parser',
    category: 'Core Workspace',
    description: 'Provides deep dive summaries on the most recently imported training feed webhook.',
    version: '1.0.0',
    ownerDashboards: ['dashboard'],
    requiredViewModel: 'HomeDashboardViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L', 'XL'],
    refreshStrategy: 'realtime',
    documentation: 'Parses incoming activities before ingestion queue normalization to display raw data metrics.',
    defaultWidth: 2,
    defaultHeight: 2
  },
  home_weekly_summary: {
    id: 'home_weekly_summary',
    title: 'Weekly Training Volume Breakdown',
    subtitle: 'Current microcycle totals and variance',
    category: 'Core Workspace',
    description: 'Calculates the cumulative distance and duration totals for the active training week.',
    version: '1.0.0',
    ownerDashboards: ['dashboard'],
    requiredViewModel: 'HomeDashboardViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'interval',
    documentation: 'Tracks microcycle volume to evaluate consistency and prevent acute workload spikes.',
    defaultWidth: 2,
    defaultHeight: 1
  },
  home_performance_metrics: {
    id: 'home_performance_metrics',
    title: 'Performance Load Matrix',
    subtitle: 'CTL, ATL, and TSB macro balances',
    category: 'Core Workspace',
    description: 'A summary matrix indicating fitness CTL, fatigue ATL, and form TSB balances.',
    version: '1.0.0',
    ownerDashboards: ['dashboard'],
    requiredViewModel: 'HomeDashboardViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L', 'XL', 'Full Width'],
    refreshStrategy: 'manual',
    documentation: 'Renders long-term chronic training load trends to highlight peaking states.',
    defaultWidth: 4,
    defaultHeight: 2
  },

  // Performance widgets
  perf_fitness_fatigue: {
    id: 'perf_fitness_fatigue',
    title: 'Fitness & Fatigue Trends',
    subtitle: 'CTL & ATL stress trajectory curves',
    category: 'Analytics Engine',
    description: 'Monitors athletic volume growth trends and cumulative fatigue levels.',
    version: '1.0.0',
    ownerDashboards: ['performance'],
    requiredViewModel: 'PerformanceOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'manual',
    documentation: 'Displays physiological adaptation rates based on training stress score (TSS/RSS) accumulation.',
    defaultWidth: 4,
    defaultHeight: 2
  },
  perf_form_balance: {
    id: 'perf_form_balance',
    title: 'Form & Recovery Balance',
    subtitle: 'Training stress balance (TSB) simulator',
    category: 'Analytics Engine',
    description: 'Tracks the training stress balance trajectory to map peaking cycles.',
    version: '1.0.0',
    ownerDashboards: ['performance'],
    requiredViewModel: 'PerformanceOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Charts the athlete form balance to pinpoint transition phases and peak readiness.',
    defaultWidth: 2,
    defaultHeight: 2
  },
  perf_season_bests: {
    id: 'perf_season_bests',
    title: 'Personal and Season Bests',
    subtitle: 'Peak performance intervals',
    category: 'Analytics Engine',
    description: 'Tracks top paced achievements across standardized running intervals.',
    version: '1.0.0',
    ownerDashboards: ['performance'],
    requiredViewModel: 'PerformanceOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Displays peak pace durations from 1 min to marathon distance to map the power curve.',
    defaultWidth: 2,
    defaultHeight: 1
  },
  perf_running_economy: {
    id: 'perf_running_economy',
    title: 'VO2max Running Economy',
    subtitle: 'Aerobic threshold and oxygen utilization efficiency',
    category: 'Analytics Engine',
    description: 'Tracks aerobic thresholds and oxygen utilization efficiency ratings.',
    version: '1.0.0',
    ownerDashboards: ['performance'],
    requiredViewModel: 'PerformanceOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'manual',
    documentation: 'Calculates structural efficiency quotients to identify submaximal metabolic cost.',
    defaultWidth: 2,
    defaultHeight: 1
  },

  // Activities widgets
  act_list_view: {
    id: 'act_list_view',
    title: 'Activity Index Directory',
    subtitle: 'Ingested raw runs database index',
    category: 'Core Workspace',
    description: 'A structural collection of all synchronized runs with status sorting.',
    version: '1.0.0',
    ownerDashboards: ['activities'],
    requiredViewModel: 'ActivitySummaryViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'realtime',
    documentation: 'Lists all database records matching search tags with status indicator marks.',
    defaultWidth: 4,
    defaultHeight: 2
  },
  act_stats_aggregation: {
    id: 'act_stats_aggregation',
    title: 'Monthly Aggregate Achievements',
    subtitle: 'Calendar month totals and pacing achievements',
    category: 'Core Workspace',
    description: 'Summarizes training counts and volume progress for the calendar month.',
    version: '1.0.0',
    ownerDashboards: ['activities'],
    requiredViewModel: 'ActivitySummaryViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'interval',
    documentation: 'Provides comparative macro metrics against previous calendar months.',
    defaultWidth: 2,
    defaultHeight: 1
  },
  act_quality_scores: {
    id: 'act_quality_scores',
    title: 'Signal Integrity and Noise Scores',
    subtitle: 'Telemetry packet complete assessment',
    category: 'Core Workspace',
    description: 'Rates GPS, HR, and Power signal coverage consistency.',
    version: '1.0.0',
    ownerDashboards: ['activities'],
    requiredViewModel: 'ActivityDetailViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Flags dropout gaps or sensor connection errors within imported training fit streams.',
    defaultWidth: 2,
    defaultHeight: 1
  },

  // Heart Rate widgets
  hr_distribution: {
    id: 'hr_distribution',
    title: 'Heart Rate Zone Distribution',
    subtitle: 'Time in physiological heart rate zones',
    category: 'Sensor Insights',
    description: 'Measures time accumulated inside physiological heart rate zones.',
    version: '1.0.0',
    ownerDashboards: ['heart_rate'],
    requiredViewModel: 'HeartRateOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L', 'XL'],
    refreshStrategy: 'manual',
    documentation: 'Evaluates intensity distribution to ensure strict polarization boundaries are obeyed.',
    defaultWidth: 2,
    defaultHeight: 2
  },
  hr_drift_coupling: {
    id: 'hr_drift_coupling',
    title: 'Cardiac Drift & Aerobic Decoupling',
    subtitle: 'Cardiovascular cost divergence ratio',
    category: 'Sensor Insights',
    description: 'Measures cardiac cost and pace-to-heart-rate divergence ratios.',
    version: '1.0.0',
    ownerDashboards: ['heart_rate'],
    requiredViewModel: 'HeartRateOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Calculates the percentage shift in cardiac output during constant-intensity threshold runs.',
    defaultWidth: 2,
    defaultHeight: 1
  },
  hr_efficiency: {
    id: 'hr_efficiency',
    title: 'Heart Rate Efficiency Coefficient',
    subtitle: 'Ratio of speed to physiological strain',
    category: 'Sensor Insights',
    description: 'Calculates the ratio of average speed to average heart rate BPM.',
    version: '1.0.0',
    ownerDashboards: ['heart_rate'],
    requiredViewModel: 'HeartRateOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'manual',
    documentation: 'Monitors long-term aerobic fitness improvements by dividing pacing velocity by heart rate effort.',
    defaultWidth: 2,
    defaultHeight: 1
  },

  // Power widgets
  power_curve: {
    id: 'power_curve',
    title: 'Power Duration Curve',
    subtitle: 'Maximum watt threshold profile',
    category: 'Sensor Insights',
    description: 'Plots the maximum wattage output achieved across logarithmic durations.',
    version: '1.0.0',
    ownerDashboards: ['power'],
    requiredViewModel: 'PowerOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'manual',
    documentation: 'Identifies neuromuscular power limits, anaerobic capacity thresholds, and aerobic potential.',
    defaultWidth: 4,
    defaultHeight: 2
  },
  power_zones: {
    id: 'power_zones',
    title: 'Power Intensity Distribution',
    subtitle: 'Calculated wattage boundaries',
    category: 'Sensor Insights',
    description: 'Calculates training time spent inside customized wattage thresholds.',
    version: '1.0.0',
    ownerDashboards: ['power'],
    requiredViewModel: 'PowerOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Analyzes muscle fatigue factors and specific energy system workloads based on FTP percentage zones.',
    defaultWidth: 2,
    defaultHeight: 2
  },
  power_efficiency: {
    id: 'power_efficiency',
    title: 'Mechanical Efficiency Index',
    subtitle: 'Watts output vs cardiovascular expense',
    category: 'Sensor Insights',
    description: 'Measures wattage output vs cardiovascular heart rate expense.',
    version: '1.0.0',
    ownerDashboards: ['power'],
    requiredViewModel: 'PowerOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'manual',
    documentation: 'Measures mechanical energy conversion rates relative to internal cardiovascular load.',
    defaultWidth: 2,
    defaultHeight: 1
  },

  // Cadence widgets
  cadence_stability: {
    id: 'cadence_stability',
    title: 'Stride Cadence Stability Rate',
    subtitle: 'Stride cadence variance and efficiency index',
    category: 'Sensor Insights',
    description: 'Tracks variance and cadence consistency indices throughout training runs.',
    version: '1.0.0',
    ownerDashboards: ['cadence'],
    requiredViewModel: 'CadenceOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Monitors biomechanical gait stability, highlighting stride pacing drift induced by fatigue.',
    defaultWidth: 2,
    defaultHeight: 2
  },
  cadence_decay: {
    id: 'cadence_decay',
    title: 'Fatigue-Induced Cadence Decay',
    subtitle: 'Stride rate erosion factor',
    category: 'Sensor Insights',
    description: 'Rates how much stride cadence drops during long threshold efforts.',
    version: '1.0.0',
    ownerDashboards: ['cadence'],
    requiredViewModel: 'CadenceOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'manual',
    documentation: 'Analyzes neuro-muscular decay indicators towards the end of long runs.',
    defaultWidth: 2,
    defaultHeight: 1
  },

  // Training Load widgets
  load_ctl_trend: {
    id: 'load_ctl_trend',
    title: 'Chronic Training Load Trajectory',
    subtitle: 'Fitness and volume growth rate indicator',
    category: 'Analytics Engine',
    description: 'Calculates long-term fitness and workload adaptation velocity.',
    version: '1.0.0',
    ownerDashboards: ['training_load'],
    requiredViewModel: 'TrainingLoadOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'manual',
    documentation: 'Measures chronic training stress balances to safe-guard progression rates.',
    defaultWidth: 4,
    defaultHeight: 2
  },
  load_ramp_rate: {
    id: 'load_ramp_rate',
    title: 'Ramp Rate Risk Indicator',
    subtitle: 'Week-over-week training stress escalation',
    category: 'Analytics Engine',
    description: 'Alerts when week-over-week training stress escalation exceeds limits.',
    version: '1.0.0',
    ownerDashboards: ['training_load'],
    requiredViewModel: 'TrainingLoadOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Detects injury risks by identifying if CTL increases faster than 6 units/week.',
    defaultWidth: 2,
    defaultHeight: 2
  },

  // Recovery widgets
  rec_readiness: {
    id: 'rec_readiness',
    title: 'Physiological Readiness Score',
    subtitle: 'HRV, TSB, and recent stress synthesis',
    category: 'Analytics Engine',
    description: 'Scores readiness factors based on HRV, TSB, and recent training stress.',
    version: '1.0.0',
    ownerDashboards: ['recovery'],
    requiredViewModel: 'RecoveryOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Balances acute strain against chronic capacities to establish structural safety caps.',
    defaultWidth: 2,
    defaultHeight: 2
  },
  rec_monotony: {
    id: 'rec_monotony',
    title: 'Overtraining Monotony Rating',
    subtitle: 'Training schedule variance evaluation',
    category: 'Analytics Engine',
    description: 'Calculates workout variance to warn against overtraining syndromes.',
    version: '1.0.0',
    ownerDashboards: ['recovery'],
    requiredViewModel: 'RecoveryOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'manual',
    documentation: 'Measures daily load deviations; static loads increase overtraining indices.',
    defaultWidth: 2,
    defaultHeight: 1
  },

  // Environment widgets
  env_heat_acclimation: {
    id: 'env_heat_acclimation',
    title: 'Heat & Humidity Acclimatization',
    subtitle: 'Thermal adaptation and dehydration limits',
    category: 'Environment & Gear',
    description: 'Rates high-temperature adaptation levels and dehydration risk caps.',
    version: '1.0.0',
    ownerDashboards: ['environment'],
    requiredViewModel: 'EnvironmentOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'manual',
    documentation: 'Evaluates cardiac output adaptations under elevated climatic stress constraints.',
    defaultWidth: 2,
    defaultHeight: 1
  },
  env_impact_pace: {
    id: 'env_impact_pace',
    title: 'Climatic Pacing Impact Analysis',
    subtitle: 'Elevation and thermal stress correction curves',
    category: 'Environment & Gear',
    description: 'Graphs pacing adjustments required for extreme elevations or heat.',
    version: '1.0.0',
    ownerDashboards: ['environment'],
    requiredViewModel: 'EnvironmentOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Utilizes environmental coefficients to normalize high-heat and elevation paces.',
    defaultWidth: 2,
    defaultHeight: 2
  },

  // Equipment widgets
  eq_shoe_mileage: {
    id: 'eq_shoe_mileage',
    title: 'Gear Cumulative Mileage Tracker',
    subtitle: 'Running shoe retirement tracking',
    category: 'Environment & Gear',
    description: 'Aggregates mileage records for running shoes, highlighting retirement marks.',
    version: '1.0.0',
    ownerDashboards: ['equipment'],
    requiredViewModel: 'EquipmentOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'manual',
    documentation: 'Provides gear deterioration indicators, sounding warnings when structural limits are breached.',
    defaultWidth: 4,
    defaultHeight: 2
  },
  eq_injury_assessment: {
    id: 'eq_injury_assessment',
    title: 'Injury Risk Assessment',
    subtitle: 'Biomechanical risk factor analysis',
    category: 'Environment & Gear',
    description: 'Monitors biomechanical risk factors based on shoe depletion levels.',
    version: '1.0.0',
    ownerDashboards: ['equipment'],
    requiredViewModel: 'EquipmentOverviewViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Correlates joint loading impact indices against passive shoe damping erosion stats.',
    defaultWidth: 2,
    defaultHeight: 2
  },

  // Connections widgets
  conn_strava: {
    id: 'conn_strava',
    title: 'Strava API Credentials Gate',
    subtitle: 'Client client secret and webhook channels',
    category: 'System Administration',
    description: 'Configures client credentials, webhook subscription IDs, and authorization tokens.',
    version: '1.0.0',
    ownerDashboards: ['connections'],
    requiredViewModel: 'SyncHealthViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'realtime',
    documentation: 'Direct API key manager gateway; enforces secure token exchanges.',
    defaultWidth: 2,
    defaultHeight: 2
  },
  conn_intervals: {
    id: 'conn_intervals',
    title: 'Intervals.icu Integration Sync',
    subtitle: 'External athletic load synchronization key',
    category: 'System Administration',
    description: 'Authenticates Intervals.icu keys to import external athletic load data.',
    version: '1.0.0',
    ownerDashboards: ['connections'],
    requiredViewModel: 'SyncHealthViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'realtime',
    documentation: 'Integrates external coaching logs and multi-sport stress indicators.',
    defaultWidth: 2,
    defaultHeight: 2
  },

  // Data Health widgets
  health_integrity: {
    id: 'health_integrity',
    title: 'Sensor Data Signal Integrity',
    subtitle: 'Telemetry packet complete and validation',
    category: 'System Administration',
    description: 'Grades overall dataset completeness across historical recordings.',
    version: '1.0.0',
    ownerDashboards: ['data_health'],
    requiredViewModel: 'DataHealthViewModel',
    requiredPermissions: [],
    supportedSizes: ['M', 'L'],
    refreshStrategy: 'manual',
    documentation: 'Grades file integrity to catch raw sensor drop-outs and satellite signal bounce.',
    defaultWidth: 2,
    defaultHeight: 2
  },
  health_anomaly_logs: {
    id: 'health_anomaly_logs',
    title: 'Telemetry Drops & Outliers Log',
    subtitle: 'Identified cadence and GPS anomalies',
    category: 'System Administration',
    description: 'Tabulates GPS dropping spikes, sensor dropout points, and pace glitches.',
    version: '1.0.0',
    ownerDashboards: ['data_health'],
    requiredViewModel: 'DataHealthViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'manual',
    documentation: 'Maintains error logs of telemetry gaps to ensure mathematical calculations remain clean.',
    defaultWidth: 4,
    defaultHeight: 2
  },

  // Settings widgets
  set_thresholds: {
    id: 'set_thresholds',
    title: 'Physiological Zone Calibrations',
    subtitle: 'Threshold pace and heart rate heart zone boundaries',
    category: 'System Administration',
    description: 'Calibrates customized threshold pace, resting HR, and power capacities.',
    version: '1.0.0',
    ownerDashboards: ['settings'],
    requiredViewModel: 'SettingsViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'manual',
    documentation: 'Establishes the base zones for RSS, IF, and power fatigue curve calculations.',
    defaultWidth: 4,
    defaultHeight: 2
  },
  set_sync_prefs: {
    id: 'set_sync_prefs',
    title: 'Automatic Sync Webhook Rules',
    subtitle: 'Cron thresholds and push sync configs',
    category: 'System Administration',
    description: 'Adjusts cron cycles, webhook trigger rules, and push alert limits.',
    version: '1.0.0',
    ownerDashboards: ['settings'],
    requiredViewModel: 'SettingsViewModel',
    requiredPermissions: [],
    supportedSizes: ['S', 'M'],
    refreshStrategy: 'manual',
    documentation: 'Tunes background synchronization checks to avoid API rate-limit caps.',
    defaultWidth: 2,
    defaultHeight: 1
  },

  // Search widgets
  search_query_input: {
    id: 'search_query_input',
    title: 'Advanced Structured Query Console',
    subtitle: 'Boolean and telemetry query inputs',
    category: 'Analytics Engine',
    description: 'Input portal for structured natural or mathematical query terms.',
    version: '1.0.0',
    ownerDashboards: ['search'],
    requiredViewModel: 'SearchResultViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'realtime',
    documentation: 'Executes boolean queries directly on normalized workout records.',
    defaultWidth: 4,
    defaultHeight: 1
  },
  search_results_grid: {
    id: 'search_results_grid',
    title: 'Filtered Results Matrix',
    subtitle: 'Search results matching parameters',
    category: 'Analytics Engine',
    description: 'Renders activity arrays and files matching custom query parameters.',
    version: '1.0.0',
    ownerDashboards: ['search'],
    requiredViewModel: 'SearchResultViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'realtime',
    documentation: 'Displays high-density match arrays returned by the Search query optimizer.',
    defaultWidth: 4,
    defaultHeight: 2
  },

  // Compare widgets
  comp_activity_selector: {
    id: 'comp_activity_selector',
    title: 'Dual Ingested Run Picker',
    subtitle: 'Target and baseline runs selector',
    category: 'Analytics Engine',
    description: 'Selects base and target activities to overlay structural streams.',
    version: '1.0.0',
    ownerDashboards: ['compare'],
    requiredViewModel: 'CompareViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'realtime',
    documentation: 'Establishes baseline and comparison targets for comparative stream overlays.',
    defaultWidth: 4,
    defaultHeight: 1
  },
  comp_delta_matrix: {
    id: 'comp_delta_matrix',
    title: 'Comparative Performance Delta Matrix',
    subtitle: 'Calculated mathematical pace, HR and power deltas',
    category: 'Analytics Engine',
    description: 'Tabulates the exact mathematical pace, HR, power, and decoupling deltas.',
    version: '1.0.0',
    ownerDashboards: ['compare'],
    requiredViewModel: 'CompareViewModel',
    requiredPermissions: [],
    supportedSizes: ['L', 'XL', 'Full Width'],
    refreshStrategy: 'manual',
    documentation: 'Computes differences down to precise percent indices to identify physiological deviations.',
    defaultWidth: 4,
    defaultHeight: 2
  }
};
